### ISSUE TITLE
background thread issue

### ISSUE THREAD

**Issue by evolkov** [Nekitosss/TableAnimator#6]
self.isEmpty в строчке
`} else if !animated || (self.isEmpty && options.contains(.withoutAnimationForEmptyTable)) {`
моет вызываться из главного потока

**Comment by patskovn** [comment]
Как я понял, проблема в том, что она в теории может вызваться не из главного потока, а ей нужен главный, верно?

**Comment by evolkov** [comment]
Да. у тебя там даже так код написан, что если это условие выполнится, то ты переходишь в main.

**Comment by patskovn** [comment]
Поправил в 4.1.2
